// Generated by scripts/gen_area_data.py

#ifndef YAQP_AREA_H
#define YAQP_AREA_H

typedef enum {
    EP1_PIONEER_2,
    EP1_FOREST_1,
    EP1_FOREST_2,
    EP1_CAVES_1,
    EP1_CAVES_2,
    EP1_CAVES_3,
    EP1_MINES_1,
    EP1_MINES_2,
    EP1_RUINS_1,
    EP1_RUINS_2,
    EP1_RUINS_3,
    EP1_UNDER_THE_DOME,
    EP1_UNDERGROUND_CHANNEL,
    EP1_MONITOR_ROOM,
    EP1_____,
    EP1_VISUAL_LOBBY,
    EP1_SPACESHIP,
    EP1_TEMPLE
} ep1_area;

typedef enum {
    EP2_LAB,
    EP2_VR_TEMPLE_ALPHA,
    EP2_VR_TEMPLE_BETA,
    EP2_VR_SPACESHIP_ALPHA,
    EP2_VR_SPACESHIP_BETA,
    EP2_CENTRAL_CONTROL_AREA,
    EP2_JUNGLE_NORTH,
    EP2_JUNGLE_EAST,
    EP2_MOUNTAIN,
    EP2_SEASIDE_DAY,
    EP2_SEABED_UPPER,
    EP2_SEABED_LOWER,
    EP2_GAL_GRYPHON,
    EP2_OLGA_FLOW,
    EP2_BARBA_RAY,
    EP2_GOL_DRAGON,
    EP2_SEASIDE_NIGHT,
    EP2_TOWER
} ep2_area;

typedef enum {
    EP4_PIONEER_2,
    EP4_CRATER_EAST,
    EP4_CRATER_WEST,
    EP4_CRATER_SOUTH,
    EP4_CRATER_NORTH,
    EP4_CRATER_INTERIOR,
    EP4_SUBTERRANEAN_DESERT_1,
    EP4_SUBTERRANEAN_DESERT_2,
    EP4_SUBTERRANEAN_DESERT_3,
    EP4_METEOR_IMPACT_SITE,
    EP4_CAVES_2
} ep4_area;

#define NUM_EP1_AREAS 18
const char* const ep1_area_names[NUM_EP1_AREAS] = {
    [EP1_PIONEER_2] = "Pioneer 2",
    [EP1_FOREST_1] = "Forest 1",
    [EP1_FOREST_2] = "Forest 2",
    [EP1_CAVES_1] = "Caves 1",
    [EP1_CAVES_2] = "Caves 2",
    [EP1_CAVES_3] = "Caves 3",
    [EP1_MINES_1] = "Mines 1",
    [EP1_MINES_2] = "Mines 2",
    [EP1_RUINS_1] = "Ruins 1",
    [EP1_RUINS_2] = "Ruins 2",
    [EP1_RUINS_3] = "Ruins 3",
    [EP1_UNDER_THE_DOME] = "Under the Dome",
    [EP1_UNDERGROUND_CHANNEL] = "Underground Channel",
    [EP1_MONITOR_ROOM] = "Monitor Room",
    [EP1_____] = "????",
    [EP1_VISUAL_LOBBY] = "Visual Lobby",
    [EP1_SPACESHIP] = "Spaceship",
    [EP1_TEMPLE] = "Temple"
};

#define NUM_EP2_AREAS 18
const char* const ep2_area_names[NUM_EP2_AREAS] = {
    [EP2_LAB] = "Lab",
    [EP2_VR_TEMPLE_ALPHA] = "VR Temple Alpha",
    [EP2_VR_TEMPLE_BETA] = "VR Temple Beta",
    [EP2_VR_SPACESHIP_ALPHA] = "VR Spaceship Alpha",
    [EP2_VR_SPACESHIP_BETA] = "VR Spaceship Beta",
    [EP2_CENTRAL_CONTROL_AREA] = "Central Control Area",
    [EP2_JUNGLE_NORTH] = "Jungle North",
    [EP2_JUNGLE_EAST] = "Jungle East",
    [EP2_MOUNTAIN] = "Mountain",
    [EP2_SEASIDE_DAY] = "Seaside Day",
    [EP2_SEABED_UPPER] = "Seabed Upper",
    [EP2_SEABED_LOWER] = "Seabed Lower",
    [EP2_GAL_GRYPHON] = "Gal Gryphon",
    [EP2_OLGA_FLOW] = "Olga Flow",
    [EP2_BARBA_RAY] = "Barba Ray",
    [EP2_GOL_DRAGON] = "Gol Dragon",
    [EP2_SEASIDE_NIGHT] = "Seaside Night",
    [EP2_TOWER] = "Tower"
};

#define NUM_EP4_AREAS 11
const char* const ep4_area_names[NUM_EP4_AREAS] = {
    [EP4_PIONEER_2] = "Pioneer 2",
    [EP4_CRATER_EAST] = "Crater East",
    [EP4_CRATER_WEST] = "Crater West",
    [EP4_CRATER_SOUTH] = "Crater South",
    [EP4_CRATER_NORTH] = "Crater North",
    [EP4_CRATER_INTERIOR] = "Crater Interior",
    [EP4_SUBTERRANEAN_DESERT_1] = "Subterranean Desert 1",
    [EP4_SUBTERRANEAN_DESERT_2] = "Subterranean Desert 2",
    [EP4_SUBTERRANEAN_DESERT_3] = "Subterranean Desert 3",
    [EP4_METEOR_IMPACT_SITE] = "Meteor Impact Site",
    [EP4_CAVES_2] = "Caves 2"
};

#endif

